
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DEBUG: "1"
      DATABASE_URL: postgres://vaow:yYyPqw23pcyxLDNa@database-1.c1ewgim2iz3q.eu-north-1.rds.amazonaws.com:5432/cracker_db
