# Generated by Django 5.2 on 2025-04-27 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('weight', models.FloatField(help_text='kg')),
                ('height', models.FloatField(help_text='cm')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentary (little to no exercise)'), (1.375, 'Lightly active (1–3 times a week)'), (1.55, 'Moderately active (3–5 times a week)'), (1.725, 'Very active (6–7 times a week)'), (1.9, 'Extra active (intense daily training)')], default=1.2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
